[package]
name = "ezdgn-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
ezdgn-core = { path = "../crates/ezdgn-core" }
libfuzzer-sys = "0.4"

[[bin]]
name = "v8_read"
path = "fuzz_targets/v8_read.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
